<a href="https://colab.research.google.com/github/deepika-3/Deepa/blob/main/Final_RA_image_seg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
!pip install nibabel matplotlib numpy scikit-image


In [20]:
import sys
print(sys.version)

3.11.12 (main, Apr  9 2025, 08:55:54) [GCC 11.4.0]


In [21]:
output_dir = "/content/sample_data/RA output"
os.makedirs(output_dir, exist_ok=True)

# Loading the .nii.gz file

nii_image = nib.load("/content/3702_left_knee.nii.gz")
image_data = nii_image.get_fdata()
print(image_data)


# Selecting a 2D slice from the 3D image (e.g., middle slice) in order to reduce computation
# and complexicity

for i in range(num_slices):
    # ... your segmentation logic ...
    image_slice = image_data[:, :, i]

    if np.max(image_slice) == 0:
        print(f"Skipping blank slice {i}")
        continue

    # Segmentation is dividing the image , seperating the object from foreground to background we have to
# Perform simple thresholding (Otsu's method) for that Applying Otsu's thresholding

    thresh = threshold_otsu(image_slice)
    binary_mask = image_slice > thresh

    # Normalize image_slice to 0-1 for proper saving
    norm_slice = (image_slice - np.min(image_slice)) / (np.ptp(image_slice) + 1e-8)

    original_path = f"{output_dir}/slice_{i:03d}_original.png"
    mask_path = f"{output_dir}/slice_{i:03d}_mask.png"

    plt.imsave(original_path, norm_slice, cmap='gray')
    plt.imsave(mask_path, binary_mask.astype(np.uint8), cmap='gray')


[[[-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  ...
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]]

 [[-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  ...
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]]

 [[-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  ...
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]
  [-1000. -1000. -1000. ... -1000. -1000. -1000.]]

 ...

 [[-3024. -3024. -3024. ... -3024. -3024. -3024.]
  [-3024. -3024. -30

In [22]:
import shutil

shutil.make_archive("/content/RA_output", 'zip', "/content/sample_data/RA output")


'/content/RA_output.zip'

In [23]:
from google.colab import files
files.download("/content/RA_output.zip")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>